insert into Club (id, Title) values (1, 'Associate Professor');
insert into Club (id, Title) values (2, 'Accounting Assistant I');
insert into Club (id, Title) values (3, 'VP Sales');
insert into Club (id, Title) values (4, 'Director of Sales');
insert into Club (id, Title) values (5, 'Technical Writer');
insert into Club (id, Title) values (6, 'Business Systems Development Analyst');
insert into Club (id, Title) values (7, 'Senior Financial Analyst');
insert into Club (id, Title) values (8, 'Assistant Media Planner');
insert into Club (id, Title) values (9, 'Account Representative II');
insert into Club (id, Title) values (10, 'Technical Writer');
insert into Club (id, Title) values (11, 'Chemical Engineer');
insert into Club (id, Title) values (12, 'Graphic Designer');
insert into Club (id, Title) values (13, 'Biostatistician I');
insert into Club (id, Title) values (14, 'Programmer II');
insert into Club (id, Title) values (15, 'VP Quality Control');
insert into Club (id, Title) values (16, 'Human Resources Manager');
insert into Club (id, Title) values (17, 'Teacher');
insert into Club (id, Title) values (18, 'Research Associate');
insert into Club (id, Title) values (19, 'Analog Circuit Design manager');
insert into Club (id, Title) values (20, 'Sales Associate');
insert into Club (id, Title) values (21, 'Business Systems Development Analyst');
insert into Club (id, Title) values (22, 'Research Nurse');
insert into Club (id, Title) values (23, 'Information Systems Manager');
insert into Club (id, Title) values (24, 'Systems Administrator III');
insert into Club (id, Title) values (25, 'VP Accounting');
insert into Club (id, Title) values (26, 'Operator');
insert into Club (id, Title) values (27, 'Financial Analyst');
insert into Club (id, Title) values (28, 'Research Associate');
insert into Club (id, Title) values (29, 'Developer IV');
insert into Club (id, Title) values (30, 'Clinical Specialist');
insert into Club (id, Title) values (31, 'Quality Control Specialist');
insert into Club (id, Title) values (32, 'Senior Editor');
insert into Club (id, Title) values (33, 'Financial Analyst');
insert into Club (id, Title) values (34, 'Nuclear Power Engineer');
insert into Club (id, Title) values (35, 'Clinical Specialist');
insert into Club (id, Title) values (36, 'Senior Financial Analyst');
insert into Club (id, Title) values (37, 'Computer Systems Analyst II');
insert into Club (id, Title) values (38, 'Statistician I');
insert into Club (id, Title) values (39, 'Community Outreach Specialist');
insert into Club (id, Title) values (40, 'Actuary');
insert into Club (id, Title) values (41, 'VP Product Management');
insert into Club (id, Title) values (42, 'Staff Accountant I');
insert into Club (id, Title) values (43, 'Web Developer IV');
insert into Club (id, Title) values (44, 'VP Accounting');
insert into Club (id, Title) values (45, 'Teacher');
insert into Club (id, Title) values (46, 'Staff Accountant I');
insert into Club (id, Title) values (47, 'Physical Therapy Assistant');
insert into Club (id, Title) values (48, 'Safety Technician II');
insert into Club (id, Title) values (49, 'Director of Sales');
insert into Club (id, Title) values (50, 'Marketing Assistant');
