insert into Course (id, Code, Name, Credits, ECTS) values (1, 'SE', 'Account Executive', 1, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (2, 'SE', 'Assistant Professor', 2, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (3, 'TH', 'Accounting Assistant I', 3, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (4, 'PT', 'Sales Associate', 3, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (5, 'FR', 'Budget/Accounting Analyst III', 1, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (6, 'RU', 'Research Nurse', 1, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (7, 'FR', 'General Manager', 3, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (8, 'TM', 'Project Manager', 1, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (9, 'ET', 'Account Representative I', 2, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (10, 'KE', 'VP Product Management', 1, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (11, 'AZ', 'Marketing Manager', 3, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (12, 'CR', 'Assistant Manager', 3, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (13, 'BR', 'Quality Engineer', 1, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (14, 'CZ', 'VP Accounting', 2, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (15, 'RU', 'Assistant Media Planner', 3, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (16, 'CN', 'Biostatistician IV', 3, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (17, 'CN', 'VP Marketing', 1, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (18, 'SE', 'Associate Professor', 1, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (19, 'ID', 'Electrical Engineer', 2, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (20, 'PH', 'Project Manager', 1, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (21, 'US', 'Environmental Tech', 3, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (22, 'ID', 'Internal Auditor', 3, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (23, 'PL', 'Structural Engineer', 1, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (24, 'PH', 'Geological Engineer', 3, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (25, 'ID', 'Paralegal', 1, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (26, 'CN', 'Clinical Specialist', 3, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (27, 'CN', 'Project Manager', 2, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (28, 'RU', 'Engineer III', 3, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (29, 'MA', 'Technical Writer', 3, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (30, 'CN', 'Speech Pathologist', 1, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (31, 'PY', 'Senior Quality Engineer', 2, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (32, 'ID', 'Web Designer II', 1, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (33, 'PL', 'Geologist IV', 3, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (34, 'RU', 'Assistant Professor', 2, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (35, 'MR', 'Accountant II', 1, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (36, 'CN', 'Help Desk Operator', 3, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (37, 'GT', 'Cost Accountant', 3, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (38, 'BA', 'Nurse', 1, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (39, 'FR', 'Web Designer III', 3, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (40, 'RU', 'Actuary', 2, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (41, 'CN', 'Community Outreach Specialist', 2, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (42, 'TH', 'Librarian', 1, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (43, 'IR', 'Chemical Engineer', 2, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (44, 'CN', 'Business Systems Development Analyst', 2, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (45, 'LY', 'Computer Systems Analyst I', 3, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (46, 'PT', 'Help Desk Operator', 2, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (47, 'RS', 'Product Engineer', 2, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (48, 'ID', 'Account Coordinator', 2, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (49, 'NL', 'Technical Writer', 2, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (50, 'BR', 'Desktop Support Technician', 2, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (51, 'CN', 'Systems Administrator I', 2, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (52, 'ID', 'Human Resources Manager', 1, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (53, 'PL', 'Physical Therapy Assistant', 2, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (54, 'CN', 'Electrical Engineer', 1, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (55, 'TH', 'Human Resources Assistant II', 1, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (56, 'CO', 'Staff Scientist', 3, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (57, 'KZ', 'Quality Engineer', 3, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (58, 'JP', 'Associate Professor', 3, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (59, 'ID', 'Programmer II', 1, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (60, 'RU', 'Staff Scientist', 1, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (61, 'TN', 'Data Coordiator', 3, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (62, 'UA', 'Software Engineer I', 3, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (63, 'BR', 'Executive Secretary', 2, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (64, 'CN', 'Assistant Manager', 3, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (65, 'SE', 'Electrical Engineer', 1, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (66, 'HN', 'Analyst Programmer', 2, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (67, 'CU', 'Assistant Media Planner', 2, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (68, 'ID', 'Marketing Assistant', 2, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (69, 'PH', 'Compensation Analyst', 3, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (70, 'GR', 'Software Test Engineer III', 3, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (71, 'RU', 'Developer I', 3, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (72, 'YE', 'Account Executive', 3, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (73, 'MX', 'Pharmacist', 2, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (74, 'US', 'Occupational Therapist', 1, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (75, 'CN', 'Sales Associate', 3, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (76, 'PE', 'VP Sales', 3, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (77, 'CA', 'Analog Circuit Design manager', 1, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (78, 'PH', 'Developer IV', 2, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (79, 'BR', 'Help Desk Operator', 3, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (80, 'PL', 'Chief Design Engineer', 3, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (81, 'TZ', 'Engineer IV', 3, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (82, 'CN', 'VP Accounting', 1, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (83, 'ET', 'Recruiting Manager', 1, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (84, 'US', 'VP Marketing', 1, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (85, 'PL', 'Sales Associate', 2, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (86, 'PE', 'Senior Cost Accountant', 1, 4);
insert into Course (id, Code, Name, Credits, ECTS) values (87, 'CN', 'Senior Sales Associate', 2, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (88, 'CN', 'Junior Executive', 3, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (89, 'PH', 'VP Quality Control', 2, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (90, 'ID', 'Cost Accountant', 3, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (91, 'US', 'Research Assistant II', 1, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (92, 'CN', 'Research Nurse', 2, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (93, 'CN', 'Chemical Engineer', 3, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (94, 'CN', 'Project Manager', 3, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (95, 'ID', 'General Manager', 1, 1);
insert into Course (id, Code, Name, Credits, ECTS) values (96, 'RU', 'Assistant Manager', 2, 5);
insert into Course (id, Code, Name, Credits, ECTS) values (97, 'KR', 'Software Test Engineer III', 1, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (98, 'PT', 'Human Resources Assistant III', 1, 3);
insert into Course (id, Code, Name, Credits, ECTS) values (99, 'ID', 'Help Desk Operator', 2, 2);
insert into Course (id, Code, Name, Credits, ECTS) values (100, 'JP', 'Graphic Designer', 3, 1);
