insert into Department (id, Code, Title) values (1, '10029', 'Continuing Education Center');
insert into Department (id, Code, Title) values (2, 'CPDI', 'Center for Professional Development and Innovation');
insert into Department (id, Code, Title) values (3, 'DEP_COMP_SCI', 'Department of Computer Sciences');
insert into Department (id, Code, Title) values (4, 'DEP_ECO_BUS', 'Department of Economics and Business');
insert into Department (id, Code, Title) values (5, 'DEP_HUMANITIES', 'Department of humanities');
insert into Department (id, Code, Title) values (6, 'DEP_INF_SYS', 'Department of Information systems');
insert into Department (id, Code, Title) values (7, 'DEP_JURIS', 'Department of Jurisprudence');
insert into Department (id, Code, Title) values (8, 'DEP_LANG_EDU', 'Department of Language Education');
insert into Department (id, Code, Title) values (9, 'DEP_MATH', 'Department of Mathematics and Natural Sciences');
insert into Department (id, Code, Title) values (10, 'DEP_SOC_SCI', 'Department of Pedagogy of Natural sciences');
insert into Department (id, Code, Title) values (11, 'MDE_CENTER', 'Center for Multidisciplinary Education');
