insert into Speciality (id, Code, Title) values (1, 'BR', 'Summer in Berlin (Sommer vorm Balkon)');
insert into Speciality (id, Code, Title) values (2, 'TN', 'Raising Victor Vargas');
insert into Speciality (id, Code, Title) values (3, 'RU', 'Rocky V');
insert into Speciality (id, Code, Title) values (4, 'ZA', 'Welcome Farewell-Gutmann (Bienvenido a Farewell-Gutmann)');
insert into Speciality (id, Code, Title) values (5, 'BL', 'The Tunnel of Love');
insert into Speciality (id, Code, Title) values (6, 'PT', 'You''re Telling Me!');
insert into Speciality (id, Code, Title) values (7, 'GR', '101 Dalmatians');
insert into Speciality (id, Code, Title) values (8, 'CZ', 'Girls Gone Dead');
insert into Speciality (id, Code, Title) values (9, 'MZ', 'Nicholas and Alexandra');
insert into Speciality (id, Code, Title) values (10, 'RU', 'Texas');
insert into Speciality (id, Code, Title) values (11, 'BG', '3 Ninjas');
insert into Speciality (id, Code, Title) values (12, 'JP', 'Night Strangler, The');
insert into Speciality (id, Code, Title) values (13, 'GR', 'Land Before Time III: The Time of the Great Giving');
insert into Speciality (id, Code, Title) values (14, 'CN', 'Shane');
insert into Speciality (id, Code, Title) values (15, 'ID', 'Return of the Living Dead Part II');
insert into Speciality (id, Code, Title) values (16, 'VN', 'The Epic of Everest');
insert into Speciality (id, Code, Title) values (17, 'RU', 'Story of Me, The (O contador de histórias)');
insert into Speciality (id, Code, Title) values (18, 'SL', 'Niko & the Way to the Stars (a.k.a. The Flight Before Christmas) (Niko - Lentäjän poika)');
insert into Speciality (id, Code, Title) values (19, 'ID', 'John Wick');
insert into Speciality (id, Code, Title) values (20, 'FR', 'False as Water (Falsk som vatten)');
insert into Speciality (id, Code, Title) values (21, 'TN', 'Trust');
insert into Speciality (id, Code, Title) values (22, 'PH', 'Prince Valiant');
insert into Speciality (id, Code, Title) values (23, 'BR', 'I Got Next');
insert into Speciality (id, Code, Title) values (24, 'CN', 'Tripper, The');
insert into Speciality (id, Code, Title) values (25, 'PE', 'Duck, You Sucker (a.k.a. Fistful of Dynamite, A) (Giù la testa)');
insert into Speciality (id, Code, Title) values (26, 'CN', 'Home Before Dark');
insert into Speciality (id, Code, Title) values (27, 'RU', 'Super');
insert into Speciality (id, Code, Title) values (28, 'CN', 'Mahogany');
insert into Speciality (id, Code, Title) values (29, 'RU', 'Viper in the Fist');
insert into Speciality (id, Code, Title) values (30, 'RS', 'Ninja Cheerleaders');
insert into Speciality (id, Code, Title) values (31, 'ID', 'Minus Man, The');
insert into Speciality (id, Code, Title) values (32, 'BR', 'Your Life in 65 (Tu vida en 65'')');
insert into Speciality (id, Code, Title) values (33, 'PL', 'Hi Diddle Diddle');
insert into Speciality (id, Code, Title) values (34, 'PH', 'Hideous Sun Demon, The');
insert into Speciality (id, Code, Title) values (35, 'ID', 'City of Hope');
insert into Speciality (id, Code, Title) values (36, 'CZ', 'Double Life of Veronique, The (Double Vie de Véronique, La)');
insert into Speciality (id, Code, Title) values (37, 'CN', 'Point, The');
insert into Speciality (id, Code, Title) values (38, 'CN', 'Prodigal Sons');
insert into Speciality (id, Code, Title) values (39, 'CN', 'Dragon Ball Z: Bardock - The Father of Goku (Doragon bôru Z: Tatta hitori no saishuu kessen - Furiiza ni itonda Z senshi Kakarotto no chichi)');
insert into Speciality (id, Code, Title) values (40, 'PS', 'Rent-A-Cop');
insert into Speciality (id, Code, Title) values (41, 'LV', 'Darkest Hour, The');
insert into Speciality (id, Code, Title) values (42, 'CN', 'Lee Daniels'' The Butler');
insert into Speciality (id, Code, Title) values (43, 'KE', 'Backdraft');
insert into Speciality (id, Code, Title) values (44, 'CN', 'Raiders of Atlantis, The');
insert into Speciality (id, Code, Title) values (45, 'CN', 'The... Beautiful Country');
insert into Speciality (id, Code, Title) values (46, 'VN', 'Changeling, The');
insert into Speciality (id, Code, Title) values (47, 'CN', 'Monster in the Closet');
insert into Speciality (id, Code, Title) values (48, 'CN', 'Affairs of Anatol, The');
insert into Speciality (id, Code, Title) values (49, 'ZW', 'Men Who Tread on the Tiger''s Tail, The (Tora no o wo fumu otokotachi)');
insert into Speciality (id, Code, Title) values (50, 'ID', 'Future Weather');
insert into Speciality (id, Code, Title) values (51, 'TN', 'Aurora');
insert into Speciality (id, Code, Title) values (52, 'NI', 'Fear City');
insert into Speciality (id, Code, Title) values (53, 'FR', 'I Accuse');
insert into Speciality (id, Code, Title) values (54, 'ID', 'Complete History of My Sexual Failures, A');
insert into Speciality (id, Code, Title) values (55, 'CN', 'Mistress');
insert into Speciality (id, Code, Title) values (56, 'PT', 'Angels Sing');
insert into Speciality (id, Code, Title) values (57, 'PH', 'Silja - nuorena nukkunut');
insert into Speciality (id, Code, Title) values (58, 'RU', 'Beer for My Horses');
insert into Speciality (id, Code, Title) values (59, 'LK', 'Nutty Professor, The');
insert into Speciality (id, Code, Title) values (60, 'PH', 'Good Luck. And Take Care of Each Other');
insert into Speciality (id, Code, Title) values (61, 'SE', 'Hansel & Gretel');
insert into Speciality (id, Code, Title) values (62, 'GR', 'Wassup Rockers');
insert into Speciality (id, Code, Title) values (63, 'BR', 'Sing Your Song');
insert into Speciality (id, Code, Title) values (64, 'XK', 'Taming of the Shrew, The');
insert into Speciality (id, Code, Title) values (65, 'PH', 'Underworld: Rise of the Lycans');
insert into Speciality (id, Code, Title) values (66, 'CN', 'Care Bears Movie II: A New Generation');
insert into Speciality (id, Code, Title) values (67, 'FR', 'Brooklyn Castle');
insert into Speciality (id, Code, Title) values (68, 'PT', 'Mickey''s The Prince and the Pauper');
insert into Speciality (id, Code, Title) values (69, 'CU', 'Unconditional');
insert into Speciality (id, Code, Title) values (70, 'BY', 'Intouchables');
insert into Speciality (id, Code, Title) values (71, 'CI', 'Street Fighter');
insert into Speciality (id, Code, Title) values (72, 'CZ', 'Hole in My Heart, A (Hål i mitt hjärta, Ett)');
insert into Speciality (id, Code, Title) values (73, 'CN', 'Goal II: Living the Dream');
insert into Speciality (id, Code, Title) values (74, 'SE', 'Charlie Countryman');
insert into Speciality (id, Code, Title) values (75, 'PH', 'Last Winter, The');
insert into Speciality (id, Code, Title) values (76, 'CN', 'Whatever Happened to Harold Smith?');
insert into Speciality (id, Code, Title) values (77, 'SE', 'Vinci');
insert into Speciality (id, Code, Title) values (78, 'PH', 'Boy');
insert into Speciality (id, Code, Title) values (79, 'GR', 'Susana (Devil and the Flesh, The)');
insert into Speciality (id, Code, Title) values (80, 'FR', 'Street of Shame (Akasen chitai)');
insert into Speciality (id, Code, Title) values (81, 'VE', 'Sky High');
insert into Speciality (id, Code, Title) values (82, 'CN', 'Eddie and the Cruisers II: Eddie Lives!');
insert into Speciality (id, Code, Title) values (83, 'PH', 'Single Girl, A (Fille seule, La)');
insert into Speciality (id, Code, Title) values (84, 'CN', 'Grand Budapest Hotel, The');
insert into Speciality (id, Code, Title) values (85, 'FR', 'I''m Here');
insert into Speciality (id, Code, Title) values (86, 'PT', 'Sons of the Desert');
insert into Speciality (id, Code, Title) values (87, 'ID', 'Greater Promise, A (Iskateli Schastya)');
insert into Speciality (id, Code, Title) values (88, 'PH', 'Hawaii');
insert into Speciality (id, Code, Title) values (89, 'ID', 'Here be Dragons');
insert into Speciality (id, Code, Title) values (90, 'JP', 'This is Our Time');
insert into Speciality (id, Code, Title) values (91, 'ZA', 'Bad Boy (Story of Danny Lester, The)');
insert into Speciality (id, Code, Title) values (92, 'AM', 'Promoter, The (Card, The)');
insert into Speciality (id, Code, Title) values (93, 'CN', 'Seize the Day');
insert into Speciality (id, Code, Title) values (94, 'CU', 'All American Orgy (Cummings Farm)');
insert into Speciality (id, Code, Title) values (95, 'CN', 'Miracle of Morgan''s Creek, The');
insert into Speciality (id, Code, Title) values (96, 'PT', 'Zero');
insert into Speciality (id, Code, Title) values (97, 'CN', 'Beverly Hills Cop II');
insert into Speciality (id, Code, Title) values (98, 'ID', 'The Plague of the Zombies');
insert into Speciality (id, Code, Title) values (99, 'NG', 'Winterhawk');
insert into Speciality (id, Code, Title) values (100, 'PL', 'Good Student, The (Mr. Gibb)');
